#! /bin/bash
yarn install --pure-lockfile &&
yarn run prisma generate &&
docker-compose -f docker-compose.yml up --build && 
yarn run prisma deploy &&
yarn run relay &&
docker build . -t engrafo ||
echo 'FAILURE' && exit 1
